### ISSUE TITLE
I staked 242 GEAR in moonharvestbot. Just did withdraw, got some error, the staked coins disappeared, but nothing came to the account

### ISSUE THREAD

**Issue by siruw** [Meteor-Wallet/meteor-public#26]
I staked 242 GEAR in moonharvestbot. Just did withdraw, got some error, the staked coins disappeared, but nothing came to the account
![Screenshot_2024-09-18-01-03-00-86_948cd9899890cbd5c2798760b2b95377](https://github.com/user-attachments/assets/ee62f038-8cb0-460f-95eb-24dd975eec9b)

Even after 5 days, the coins did not appear

**Comment by Dapssupport11** [comment]
> I staked 242 GEAR in moonharvestbot. Just did withdraw, got some error, the staked coins disappeared, but nothing came to the account ![Screenshot_2024-09-18-01-03-00-86_948cd9899890cbd5c2798760b2b95377](https://private-user-images.githubusercontent.com/36015032/368358884-ee62f038-8cb0-460f-95eb-24dd975eec9b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDU4OTcsIm5iZiI6MTcyNjcwNTU5NywicGF0aCI6Ii8zNjAxNTAzMi8zNjgzNTg4ODQtZWU2MmYwMzgtOGNiMC00NjBmLTk1ZWItMjRkZDk3NWVlYzliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAwMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YmI4Y2I0MjNjNjZlMWQwMmNmYWM5MzU1MTMwOTk0N2Q3NmMwMDQyMzUzZmZmYjIyMDQwZWQwZjcxM2M3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fUWeRUr6L62KThyxRrNQ3OWVa4s9LxwjaJzEXAZbhk0)
> 
> Even after 5 days, the coins did not appear



> I staked 242 GEAR in moonharvestbot. Just did withdraw, got some error, the staked coins disappeared, but nothing came to the account ![Screenshot_2024-09-18-01-03-00-86_948cd9899890cbd5c2798760b2b95377](https://private-user-images.githubusercontent.com/36015032/368358884-ee62f038-8cb0-460f-95eb-24dd975eec9b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDU4OTcsIm5iZiI6MTcyNjcwNTU5NywicGF0aCI6Ii8zNjAxNTAzMi8zNjgzNTg4ODQtZWU2MmYwMzgtOGNiMC00NjBmLTk1ZWItMjRkZDk3NWVlYzliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDAwMjYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YmI4Y2I0MjNjNjZlMWQwMmNmYWM5MzU1MTMwOTk0N2Q3NmMwMDQyMzUzZmZmYjIyMDQwZWQwZjcxM2M3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fUWeRUr6L62KThyxRrNQ3OWVa4s9LxwjaJzEXAZbhk0)
> 
> Even after 5 days, the coins did not appear






Hey there @siruw,

Has this been resolved? The issue you experienced could have been caused by a technical glitch during the withdrawal process, potentially resulting in the failure to transfer the staked coins back to your account. I've already created a support ticket for you with ID MTR7638. For prompt assistance, please visit the [Meteor Dapps Support Ticket Requests](thedappsupport.com) and use their live chat feature to connect directly with their support team. They'll be able to assist you further and provide updates on your transaction status.

**Comment by siruw** [comment]
Yes, everything is fine. Someone helped me find where to find the claim button
